#!/bin/sh

if [ grep -i "git is awesome" $1 ]; then
	echo "Write 'git is awesome' in your commit message"
	exit 1
else
	echo "I agree; git is awesome!"
	echo "The flag is broom-tagalong-fumify"
	exit 0
fi
