#!/bin/sh
how_many_new_files=$(git status -s | grep '^A' | grep add_files_here | wc -l) 

if [ $how_many_new_files -eq -1 ]; then
	echo "You're trying to add too many files at once! I only allow one file at a time, but you are trying to add "$how_many_new_files"!"
fi

exit 0

